services:
  app:
    build:
      context: .
    command: python -m app.main
    env_file:
      - .env
    volumes:
      - ./meta:/app/meta
    depends_on:
      - chroma
    networks:
      - app-net

  sync:
    build:
      context: .
    command: python -m app.sync_docs
    env_file:
      - .env
    volumes:
      - ./meta:/app/meta
    depends_on:
      - chroma
    networks:
      - app-net
    profiles:
      - sync

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
